### ISSUE TITLE
License

### ISSUE THREAD

**Issue by kixxauth** [creationix/stack#4]
I know it's kind of silly for something as small and intuitive as Stack, but Tim, would you mind putting a license on this?

**Comment by creationix** [comment]
Is MIT fine?

**Comment by kixxauth** [comment]
Yeah, MIT would be great.

It's up to you, obviously.

I just wanted some indication if it fell under default copyright law (which prohibits adaptive works) or if you intended to allow forks, etc. That's all.

**Comment by christianbundy** [comment]
Sorry to bump, but I would still *love* a license in this repo.

**Comment by christianbundy** [comment]
@creationix  Anything I can do to help with this?

**Comment by creationix** [comment]
@christianbundy This was added over 5 years ago.  Are you needing something else?
https://github.com/creationix/stack/blob/master/LICENSE

**Comment by christianbundy** [comment]
Oops! I think my issue is that the licensed version wasn't posted to npm, so when I `npm install` it complains that the repo doesn't have a license. If you feel like it and have free time, it would be great to have the license reflected in the npm registry ([link](https://www.npmjs.com/package/stack)), but if you don't then no worries, I can ignore the warning.
